version: "2"
services:

    lb:
      image: dockercloud/haproxy:1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - 8080:80
      links:
        - nginx
        - php

    nginx:
      image: nginx
      volumes:
        - ./src:/usr/share/nginx/html
      environment:
        - VIRTUAL_HOST_WEIGHT=2
        - VIRTUAL_HOST=*/assets/*

    php:
      build: ./build/php
      volumes:
        - ./src/public:/var/www/html
      links:
        - db
      environment:
        - VIRTUAL_HOST_WEIGHT=1
        - VIRTUAL_HOST=*

    db:
        image: mariadb:10.3
        container_name: lab_mariadb
        restart: always
        volumes:
        - ./build/mysql:/docker-entrypoint-initdb.d
        - ./tmp/mysql:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=123132123
          - MYSQL_DATABASE=jeban
          - MYSQL_USER=jeban
          - MYSQL_PASSWORD=123456
