version: '2'
services:

    db:
        image: mariadb:10.3
        container_name: lab_mariadb
        restart: always
        volumes:
          - ./mysql/initdb/:/docker-entrypoint-initdb.d
          - ./mysql/data/:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=123123123
          - MYSQL_DATABASE=jeban_db
          - MYSQL_USER=jeban
          - MYSQL_PASSWORD=123456
    php:
        image: php:7-fpm-alpine
        container_name: lab_php-fpm
        restart: always
        volumes:
          - ./src/:/var/www/html
        expose:
          - "9000"
    nginx:
        image: nginx:alpine
        container_name: lab_nginx
        restart: always
        volumes:
          - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
          - ./nginx/conf.d:/etc/nginx/conf.d:ro
        volumes_from:
          - php
        ports:
          - 8000:80
    pma:
        image: phpmyadmin/phpmyadmin
        container_name: lab_phpmyadmin
        restart: always
        ports:
          - "8001:80"
